PE_6_test/Q2/Pages/Student/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Q2.DTOs;

namespace Q2.Pages.Student
{
    public class DetailModel : PageModel
    {
        public void OnGet(int id)
        {
            HttpClient _httpCilent = new HttpClient();
            HttpResponseMessage response = _httpCilent.GetAsync($"http://localhost:5000/api/Student/Detail?id={id}").Result;
            ViewData["student"] = response.Content.ReadFromJsonAsync<StudentDetailDTO>().Result;
        }
    }
}

PE_6_test/Q2/Pages/Student/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Q2.DTOs;

namespace Q2.Pages.Student
{
    public class ListModel : PageModel
    {
        [BindProperty]
        public string id_s { get; set; }
        public void OnGet()
        {
            HttpClient _httpCilent = new HttpClient();
            HttpResponseMessage response = _httpCilent.GetAsync("http://localhost:5000/api/Student/List").Result;
            ViewData["students"] = response.Content.ReadFromJsonAsync<List<StudentDTO>>().Result;

        }

        public void OnGetDelete(int id)
        {
            HttpClient _httpCilent = new HttpClient();
            HttpResponseMessage response = _httpCilent.PostAsync($"http://localhost:5000/api/Student/Delete/{id}", null).Result;
            OnGet();

        }

        public void OnPost(int id_s)
        {
            HttpClient _httpCilent = new HttpClient();
            HttpResponseMessage response = _httpCilent.GetAsync($"http://localhost:5000/api/Student/List").Result;
            ViewData["students"] = response.Content.ReadFromJsonAsync<List<StudentDTO>>().Result.Where(s => s.Id == id_s).ToList();
            ViewData["ids"] = id_s;


        }

        public void OnPostByDate(DateTime dob)
        {
            string dobStr = dob.ToString("MM/dd/yyyy");
            HttpClient _httpCilent = new HttpClient();
            HttpResponseMessage response = _httpCilent.GetAsync($"http://localhost:5000/api/Student/List").Result;
            ViewData["students"] = response.Content.ReadFromJsonAsync<List<StudentDTO>>().Result.Where(s => s.Dob == dobStr).ToList();
            ViewData["ids"] = id_s;


        }


    }
}

PE_6_test/Q2/Pages/Student/Detail.cshtml
@page
@using Q2.DTOs
@model Q2.Pages.Student.DetailModel
@{
    var stu = ViewData["student"] as StudentDetailDTO;
}
<h1>@stu.FullName</h1>
<h2>@stu.CPA</h2>

PE_6_test/Q2/Pages/Student/List.cshtml
@page
@using Q2.DTOs

@model Q2.Pages.Student.ListModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var listStudents = ViewData["students"] as List<StudentDTO>;
    var s_id = (int?) ViewData["ids"];

}

<h1>Search by id</h1>
<form method="post">
    Id: <input type="text" name="id_s" value=@s_id />
    <input type="submit" value="Search"/>
</form>

<form method="post" asp-page-handler="ByDate">
    Id: <input type="text" name="dob"  />
    <input type="submit" value="Search By Date" />
</form>



<h1>List of Students</h1>

<table border="1">
    <thead>
        <th>StudentsId</th>
        <th>FullName</th>
        <th>LecturerName</th>
        <th>Dob</th>
        <th>Gender</th>
        <th>Action</th>
    </thead>
    <tbody>
        @foreach(var s in listStudents)
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.FullName</td>
                <td>@s.LecturerName</td>
                <td>@s.Dob</td>
                <td>@s.Gender</td>
                <td>
                    <a href="/Student/Detail?id=@s.Id">Detail</a>
                    <a href="/Student/List?id=@s.Id&handler=Delete">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>